[package]
name = "pocket-ic-tests"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false
rust-version = { workspace = true }

[dependencies]
candid = { workspace = true, features = ["value"] }
pocket-ic-harness = { workspace = true }
serde = { workspace = true, features = ["derive"] }
test-canister = { workspace = true }
tokio = { workspace = true, features = ["full"] }
