[package]
name = "pocket-ic-harness-macro"
version = { workspace = true }
authors = { workspace = true }
documentation = "https://docs.rs/pocket-ic-harness-macro/"
edition = { workspace = true }
include = ["src/**/*", "../../LICENSE", "README.md", "../../CHANGELOG.md"]
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Proc-macro for pocket-ic-harness test attribute."

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
